// <auto-generated />
using System;
using CliCarProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliCarProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228171338_views")]
    partial class views
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CliCarProject.Models.Classes.Acao", b =>
                {
                    b.Property<int>("IdAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Acao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAcao"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdTipoAcao")
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoAcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoAlvo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAcao")
                        .HasName("PK__Acao__4EE45891E21367C6");

                    b.HasIndex("IdTipoAcao");

                    b.ToTable("Acao", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Administrador", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Utilizador");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Anuncio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnuncio"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime?>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Ativo");

                    b.Property<int>("IdLocalizacao")
                        .HasColumnType("int")
                        .HasColumnName("ID_Localizacao");

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Veiculo");

                    b.Property<string>("IdVendedor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Vendedor");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Visualizacoes")
                        .HasColumnType("int");

                    b.HasKey("IdAnuncio")
                        .HasName("PK__Anuncio__D8875FB6A2E65C9A");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdVeiculo");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Anuncio", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Classe");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdClasse")
                        .HasName("PK__Classe__7C4BBB54FAA85776");

                    b.ToTable("Classe", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Combustivel", b =>
                {
                    b.Property<int>("IdCombustivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Combustivel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombustivel"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCombustivel")
                        .HasName("PK__Combusti__F8AAF41E4F0B740D");

                    b.ToTable("Combustivel", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Compra", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Anuncio");

                    b.Property<DateTime?>("DataCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Concluida");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Comprador");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdAnuncio")
                        .HasName("PK__Compra__D8875FB64E0009E5");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Comprador", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Utilizador");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Contacto")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Comprador", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Favorito", b =>
                {
                    b.Property<int>("IdFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Favorito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFavorito"));

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Anuncio");

                    b.Property<string>("IdUtilizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Utilizador");

                    b.HasKey("IdFavorito");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex(new[] { "IdUtilizador", "IdAnuncio" }, "IX_Favorito_User_Anuncio")
                        .IsUnique();

                    b.ToTable("Favorito", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.FiltrosFavorito", b =>
                {
                    b.Property<int>("IdFiltroFavorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FiltroFavorito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiltroFavorito"));

                    b.Property<int?>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Classe");

                    b.Property<int?>("IdCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("ID_Combustivel");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Comprador");

                    b.Property<int?>("IdLocalizacao")
                        .HasColumnType("int")
                        .HasColumnName("ID_Localizacao");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("ID_Marca");

                    b.HasKey("IdFiltroFavorito")
                        .HasName("PK__FiltrosF__410905C7C5E79498");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdCombustivel");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdMarca");

                    b.ToTable("FiltrosFavoritos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.HistoricoAco", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Historico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime?>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("IdAcao")
                        .HasColumnType("int")
                        .HasColumnName("ID_Acao");

                    b.Property<int?>("IdAlvo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Alvo");

                    b.Property<string>("IdUtilizador")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Utilizador");

                    b.Property<string>("Razao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoAlvo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdHistorico")
                        .HasName("PK__Historic__ECA887958CE82E6F");

                    b.HasIndex("IdAcao");

                    b.ToTable("HistoricoAcoes");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Imagem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<int>("IdVeiculo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Veiculo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdImagem")
                        .HasName("PK__Imagem__5A31EE7D452C5C8C");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("Imagem", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Localizacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLocalizacao")
                        .HasName("PK__Localiza__72A2EF98171EE69F");

                    b.ToTable("Localizacao", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMarca")
                        .HasName("PK__Marca__9B8F8DB2441923EF");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("ID_Marca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdModelo")
                        .HasName("PK__Modelo__813C2372542DB0DE");

                    b.HasIndex("IdMarca");

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.SitePageView", b =>
                {
                    b.Property<int>("IdSitePageView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SitePageView");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSitePageView"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSitePageView");

                    b.ToTable("SitePageView", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.TipoAcao", b =>
                {
                    b.Property<int>("IdTipoAcao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TipoAcao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoAcao"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoAcao")
                        .HasName("PK__TipoAcao__D8411B34A8D3749C");

                    b.ToTable("TipoAcao", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Veiculo", b =>
                {
                    b.Property<int>("IdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Veiculo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVeiculo"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Caixa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<int>("IdClasse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Classe");

                    b.Property<int>("IdCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("ID_Combustivel");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("ID_Modelo");

                    b.Property<string>("IdVendedor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Vendedor");

                    b.Property<int?>("Quilometragem")
                        .HasColumnType("int");

                    b.HasKey("IdVeiculo")
                        .HasName("PK__Veiculo__808FFECF1FB610CC");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdCombustivel");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdVendedor");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Vendedor", b =>
                {
                    b.Property<string>("IdUtilizador")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Utilizador");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Contacto")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .IsFixedLength();

                    b.Property<string>("Nif")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("char(9)")
                        .HasColumnName("NIF")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdUtilizador");

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.VisitaReserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendente");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("ID_Anuncio");

                    b.Property<string>("IdComprador")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ID_Comprador");

                    b.HasKey("IdReserva")
                        .HasName("PK__VisitaRe__12CAD9F4E4121AE5");

                    b.HasIndex("IdAnuncio");

                    b.ToTable("VisitaReserva", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Acao", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.TipoAcao", "IdTipoAcaoNavigation")
                        .WithMany("Acaos")
                        .HasForeignKey("IdTipoAcao")
                        .IsRequired()
                        .HasConstraintName("FK__Acao__ID_TipoAca__7B5B524B");

                    b.Navigation("IdTipoAcaoNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Administrador", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdUtilizadorNavigation")
                        .WithOne()
                        .HasForeignKey("CliCarProject.Models.Classes.Administrador", "IdUtilizador")
                        .IsRequired()
                        .HasConstraintName("FK_Administrador_AspNetUsers");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Anuncio", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Localizacao", "IdLocalizacaoNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("IdLocalizacao")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__ID_Loca__619B8048");

                    b.HasOne("CliCarProject.Models.Classes.Veiculo", "IdVeiculoNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("IdVeiculo")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__ID_Veic__5FB337D6");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdVendedorNavigation")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Anuncio_AspNetUsers");

                    b.Navigation("IdLocalizacaoNavigation");

                    b.Navigation("IdVeiculoNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Compra", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Anuncio", "IdAnuncioNavigation")
                        .WithOne("Compra")
                        .HasForeignKey("CliCarProject.Models.Classes.Compra", "IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__ID_Anunc__75A278F5");

                    b.Navigation("IdAnuncioNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Comprador", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdUtilizadorNavigation")
                        .WithOne()
                        .HasForeignKey("CliCarProject.Models.Classes.Comprador", "IdUtilizador")
                        .IsRequired()
                        .HasConstraintName("FK_Comprador_AspNetUsers");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Favorito", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("IdAnuncio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Favorito_Anuncio");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Utilizador")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Favorito_AspNetUsers");

                    b.Navigation("Anuncio");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.FiltrosFavorito", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Classe", "IdClasseNavigation")
                        .WithMany("FiltrosFavoritos")
                        .HasForeignKey("IdClasse")
                        .HasConstraintName("FK__FiltrosFa__ID_Cl__693CA210");

                    b.HasOne("CliCarProject.Models.Classes.Combustivel", "IdCombustivelNavigation")
                        .WithMany("FiltrosFavoritos")
                        .HasForeignKey("IdCombustivel")
                        .HasConstraintName("FK__FiltrosFa__ID_Co__68487DD7");

                    b.HasOne("CliCarProject.Models.Classes.Localizacao", "IdLocalizacaoNavigation")
                        .WithMany("FiltrosFavoritos")
                        .HasForeignKey("IdLocalizacao")
                        .HasConstraintName("FK__FiltrosFa__ID_Lo__6A30C649");

                    b.HasOne("CliCarProject.Models.Classes.Marca", "IdMarcaNavigation")
                        .WithMany("FiltrosFavoritos")
                        .HasForeignKey("IdMarca")
                        .HasConstraintName("FK__FiltrosFa__ID_Ma__6B24EA82");

                    b.Navigation("IdClasseNavigation");

                    b.Navigation("IdCombustivelNavigation");

                    b.Navigation("IdLocalizacaoNavigation");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.HistoricoAco", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Acao", "IdAcaoNavigation")
                        .WithMany("HistoricoAcos")
                        .HasForeignKey("IdAcao")
                        .IsRequired()
                        .HasConstraintName("FK__Historico__ID_Ac__7F2BE32F");

                    b.Navigation("IdAcaoNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Imagem", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Veiculo", "IdVeiculoNavigation")
                        .WithMany("Imagems")
                        .HasForeignKey("IdVeiculo")
                        .IsRequired()
                        .HasConstraintName("FK__Imagem__ID_Veicu__6477ECF3");

                    b.Navigation("IdVeiculoNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Modelo", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Marca", "IdMarcaNavigation")
                        .WithMany("Modelos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK__Modelo__ID_Marca__5165187F");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Veiculo", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Classe", "IdClasseNavigation")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdClasse")
                        .IsRequired()
                        .HasConstraintName("FK__Veiculo__ID_Clas__59FA5E80");

                    b.HasOne("CliCarProject.Models.Classes.Combustivel", "IdCombustivelNavigation")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdCombustivel")
                        .IsRequired()
                        .HasConstraintName("FK__Veiculo__ID_Comb__59063A47");

                    b.HasOne("CliCarProject.Models.Classes.Marca", "IdMarcaNavigation")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK_Veiculo_Marca");

                    b.HasOne("CliCarProject.Models.Classes.Modelo", "IdModeloNavigation")
                        .WithMany("Veiculos")
                        .HasForeignKey("IdModelo")
                        .IsRequired()
                        .HasConstraintName("FK__Veiculo__ID_Mode__5812160E");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdVendedorNavigation")
                        .WithMany()
                        .HasForeignKey("IdVendedor")
                        .HasConstraintName("FK_Veiculo_AspNetUsers");

                    b.Navigation("IdClasseNavigation");

                    b.Navigation("IdCombustivelNavigation");

                    b.Navigation("IdMarcaNavigation");

                    b.Navigation("IdModeloNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Vendedor", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdUtilizadorNavigation")
                        .WithOne()
                        .HasForeignKey("CliCarProject.Models.Classes.Vendedor", "IdUtilizador")
                        .IsRequired()
                        .HasConstraintName("FK_Vendedor_AspNetUsers");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.VisitaReserva", b =>
                {
                    b.HasOne("CliCarProject.Models.Classes.Anuncio", "IdAnuncioNavigation")
                        .WithMany("VisitaReservas")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__VisitaRes__ID_An__6FE99F9F");

                    b.Navigation("IdAnuncioNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Acao", b =>
                {
                    b.Navigation("HistoricoAcos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Anuncio", b =>
                {
                    b.Navigation("Compra");

                    b.Navigation("VisitaReservas");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Classe", b =>
                {
                    b.Navigation("FiltrosFavoritos");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Combustivel", b =>
                {
                    b.Navigation("FiltrosFavoritos");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Localizacao", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("FiltrosFavoritos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Marca", b =>
                {
                    b.Navigation("FiltrosFavoritos");

                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Modelo", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.TipoAcao", b =>
                {
                    b.Navigation("Acaos");
                });

            modelBuilder.Entity("CliCarProject.Models.Classes.Veiculo", b =>
                {
                    b.Navigation("Anuncios");

                    b.Navigation("Imagems");
                });
#pragma warning restore 612, 618
        }
    }
}
